export const BOTTOM_TAB_CHANGED = 'BOTTOM_TAB_CHANGED';

export const EDITABLE_TOP_TAB_CHANGED = 'EDITABLE_TOP_TAB_CHANGED';

export const DARK_MODE_CHANGED = 'DARK_MODE_CHANGED';

export const WEBVIEW_URL_CHANGED = 'WEBVIEW_URL_CHANGED';

export const WEBSOCKET_URL_CHANGED = 'WEBSOCKET_URL_CHANGED';
